### ISSUE TITLE
Error when saving hdf5 files using phconvert.

### ISSUE THREAD

**Issue by AndersBarth** [Photon-HDF5/phconvert#9]
When using the save_photon_hdf5 routine, I encounter an error because the version string of phconvert 0.6.8 is of unicode format, which is not compatible with the hdf5 saving routine. This issue occurs because json.loads as used in `_version.py` will return a unicode object.
I managed to circumvent this problem by ensuring that the `__version__` argument is a python string by changing line 41 of hdf5.py:
`__version__ = get_versions()['version']`
to
`__version__ = str(get_versions()['version'])`
I am using OSX and python2.7.

**Comment by tritemio** [comment]
Thanks for the bug report.

By looking at the code, it looks like your analysis is correct. Normally, phconvert encodes all the strings to binary before saving to HDF5 (see [this line](https://github.com/Photon-HDF5/phconvert/blob/0.6.8/phconvert/hdf5.py#L131)). This operation does nothing on python 2 since strings are already binary (and we only use ASCII). However, if an input string is unicode on python 2 (like `__version__`), it will fail the test `isinstance(obj, str)` and it will not be encoded.

I think your solution should work on both python 2 and 3. Would you like to submit a Pull Request (PR) with your fix so you can be properly credited?

PS: In case you are not familiar with git, the easiest way (for such a small change) is editing the file hdf5.py online on github and clicking on **Propose file change**. If you put #9 in the commit message the PR will also be linked to this issue.

**Comment by AndersBarth** [comment]
Thanks for the quick reply! I made the PR.

**Comment by tritemio** [comment]
PR #9 merged. Also, to help catching this kind of errors,  I made it easier to automatically run all the notebook on both python2 and python3 (532c6518b12eeda86accdd88cd9103e2f9a5109f) using this  [test notebook](https://github.com/Photon-HDF5/phconvert/blob/master/tests/Execute%20notebooks.ipynb).Interestignly, this required a patch to nbconvert https://github.com/jupyter/nbconvert/pull/177 which was merged yesterday.

Closing.
